#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="${ROKID_ROOT_DIR:-$(cd "$APP_DIR/../.." && pwd)}"
LOG_DIR="$ROOT_DIR/logs"
VENV_DIR="${ROKID_VENV_DIR:-$ROOT_DIR/runtime/venv}"
SESSION_NAME="rokid-backend"
HOST="0.0.0.0"
PORT="9080"
PUBLIC_HOST="${ROKID_PUBLIC_HOST:-jay.tail8dd874.ts.net}"
ENABLE_HLS="0"
ENABLE_MJPEG="0"
ENABLE_LOCAL_PREVIEW="0"
LOCAL_PREVIEW_DISPLAY=":0"
LOCAL_PREVIEW_XAUTHORITY="/run/user/1000/gdm/Xauthority"
LOCAL_PREVIEW_MODE="${ROKID_LOCAL_PREVIEW_MODE:-ffplay_overlay}"
LOCAL_PREVIEW_SINK="xvimagesink"
AI_MODE="${ROKID_AI_MODE:-inline_trt_yolo26}"
AI_IDLE_UNLOAD_MS="${ROKID_AI_IDLE_UNLOAD_MS:-45000}"
RESULT_INTERVAL_MS="${ROKID_RESULT_INTERVAL_MS:-120}"
SCENE_CONFIDENCE="${ROKID_SCENE_CONFIDENCE:-0.30}"
SCENE_MAX_DET="${ROKID_SCENE_MAX_DET:-60}"
SCENE_TRACK_HOLD_MS="${ROKID_SCENE_TRACK_HOLD_MS:-450}"
SCENE_TRACK_MATCH_IOU="${ROKID_SCENE_TRACK_MATCH_IOU:-0.28}"
SCENE_TRACK_MIN_HITS="${ROKID_SCENE_TRACK_MIN_HITS:-2}"
SCENE_TRACK_INSTANT_CONFIDENCE="${ROKID_SCENE_TRACK_INSTANT_CONFIDENCE:-0.58}"
SCENE_EXTERNAL_CMD="${ROKID_SCENE_EXTERNAL_CMD:-}"
DEFAULT_MODEL_DIR="$ROOT_DIR/models"
if [[ ! -f "$DEFAULT_MODEL_DIR/yolo26_labels.txt" && -d "$(cd "$ROOT_DIR/.." && pwd)/models" ]]; then
  DEFAULT_MODEL_DIR="$(cd "$ROOT_DIR/.." && pwd)/models"
fi
YOLO26_MODEL_NAME="${ROKID_YOLO26_MODEL_NAME:-yolo26_shared}"
YOLO26_ENGINE_PATH="${ROKID_YOLO26_ENGINE_PATH:-$DEFAULT_MODEL_DIR/yolo26s_b1_gpu0_fp16.engine}"
YOLO26_LABELS_PATH="${ROKID_YOLO26_LABELS_PATH:-$DEFAULT_MODEL_DIR/yolo26_labels.txt}"
ASR_BACKEND="${ROKID_ASR_BACKEND:-openai_realtime_skills}"
VOICE_IDLE_UNLOAD_MS="${ROKID_VOICE_BACKEND_IDLE_UNLOAD_MS:-60000}"
VOICE_STARTUP_TIMEOUT_MS="${ROKID_VOICE_BACKEND_STARTUP_TIMEOUT_MS:-15000}"
VOICE_AUTO_WAKE_ON_SESSION="${ROKID_VOICE_AUTO_WAKE_ON_SESSION:-1}"
LOCAL_ASR_PROFILE="${ROKID_LOCAL_ASR_PROFILE:-vi_small_low_power}"
LOCAL_ASR_REQUEST_FORMAT="${ROKID_LOCAL_ASR_REQUEST_FORMAT:-binary_wav}"
LOCAL_ASR_TRANSCRIBE_URL="${ROKID_LOCAL_ASR_TRANSCRIBE_URL:-}"
LOCAL_ASR_HEALTH_URL="${ROKID_LOCAL_ASR_HEALTH_URL:-}"
LOCAL_ASR_START_CMD="${ROKID_LOCAL_ASR_START_CMD:-}"
LOCAL_ASR_STOP_CMD="${ROKID_LOCAL_ASR_STOP_CMD:-}"
LOCAL_ASR_COMMAND_TEMPLATE="${ROKID_LOCAL_ASR_COMMAND_TEMPLATE:-}"
LOCAL_ASR_RESPONSE_TEXT_PATH="${ROKID_LOCAL_ASR_RESPONSE_TEXT_PATH:-text}"
ALLOW_OPENAI_STT_FALLBACK="${ROKID_ALLOW_OPENAI_STT_FALLBACK:-0}"
ALLOW_OPENAI_ROUTER_FALLBACK="${ROKID_ALLOW_OPENAI_ROUTER_FALLBACK:-0}"

mkdir -p "$LOG_DIR"

pkill -f "uvicorn app.main:app --host $HOST --port $PORT" >/dev/null 2>&1 || true
tmux kill-session -t "$SESSION_NAME" >/dev/null 2>&1 || true
pkill -f "gst-launch-1.0 -q fdsrc" >/dev/null 2>&1 || true
pkill -f "ffplay -hide_banner -loglevel error -fflags nobuffer" >/dev/null 2>&1 || true

tmux new-session -d -s "$SESSION_NAME" \
  "cd '$APP_DIR' && export ROKID_ROOT_DIR='$ROOT_DIR' ROKID_PUBLIC_HOST='$PUBLIC_HOST' ROKID_DEFAULT_MODE='standby' ROKID_ENABLE_HLS='$ENABLE_HLS' ROKID_ENABLE_MJPEG='$ENABLE_MJPEG' ROKID_ENABLE_LOCAL_PREVIEW='$ENABLE_LOCAL_PREVIEW' ROKID_LOCAL_PREVIEW_DISPLAY='$LOCAL_PREVIEW_DISPLAY' ROKID_LOCAL_PREVIEW_XAUTHORITY='$LOCAL_PREVIEW_XAUTHORITY' ROKID_LOCAL_PREVIEW_MODE='$LOCAL_PREVIEW_MODE' ROKID_LOCAL_PREVIEW_SINK='$LOCAL_PREVIEW_SINK' ROKID_AI_MODE='$AI_MODE' ROKID_AI_IDLE_UNLOAD_MS='$AI_IDLE_UNLOAD_MS' ROKID_RESULT_INTERVAL_MS='$RESULT_INTERVAL_MS' ROKID_SCENE_CONFIDENCE='$SCENE_CONFIDENCE' ROKID_SCENE_MAX_DET='$SCENE_MAX_DET' ROKID_SCENE_TRACK_HOLD_MS='$SCENE_TRACK_HOLD_MS' ROKID_SCENE_TRACK_MATCH_IOU='$SCENE_TRACK_MATCH_IOU' ROKID_SCENE_TRACK_MIN_HITS='$SCENE_TRACK_MIN_HITS' ROKID_SCENE_TRACK_INSTANT_CONFIDENCE='$SCENE_TRACK_INSTANT_CONFIDENCE' ROKID_SCENE_EXTERNAL_CMD='$SCENE_EXTERNAL_CMD' ROKID_YOLO26_MODEL_NAME='$YOLO26_MODEL_NAME' ROKID_YOLO26_ENGINE_PATH='$YOLO26_ENGINE_PATH' ROKID_YOLO26_LABELS_PATH='$YOLO26_LABELS_PATH' ROKID_ASR_BACKEND='$ASR_BACKEND' ROKID_VOICE_BACKEND_IDLE_UNLOAD_MS='$VOICE_IDLE_UNLOAD_MS' ROKID_VOICE_BACKEND_STARTUP_TIMEOUT_MS='$VOICE_STARTUP_TIMEOUT_MS' ROKID_VOICE_AUTO_WAKE_ON_SESSION='$VOICE_AUTO_WAKE_ON_SESSION' ROKID_LOCAL_ASR_PROFILE='$LOCAL_ASR_PROFILE' ROKID_LOCAL_ASR_REQUEST_FORMAT='$LOCAL_ASR_REQUEST_FORMAT' ROKID_LOCAL_ASR_TRANSCRIBE_URL='$LOCAL_ASR_TRANSCRIBE_URL' ROKID_LOCAL_ASR_HEALTH_URL='$LOCAL_ASR_HEALTH_URL' ROKID_LOCAL_ASR_START_CMD='$LOCAL_ASR_START_CMD' ROKID_LOCAL_ASR_STOP_CMD='$LOCAL_ASR_STOP_CMD' ROKID_LOCAL_ASR_COMMAND_TEMPLATE='$LOCAL_ASR_COMMAND_TEMPLATE' ROKID_LOCAL_ASR_RESPONSE_TEXT_PATH='$LOCAL_ASR_RESPONSE_TEXT_PATH' ROKID_ALLOW_OPENAI_STT_FALLBACK='$ALLOW_OPENAI_STT_FALLBACK' ROKID_ALLOW_OPENAI_ROUTER_FALLBACK='$ALLOW_OPENAI_ROUTER_FALLBACK' && exec '$VENV_DIR/bin/uvicorn' app.main:app --host $HOST --port $PORT >> '$LOG_DIR/backend_mvp.out' 2>> '$LOG_DIR/backend_mvp.err'"

sleep 3
curl -fsS "http://127.0.0.1:$PORT/health"
